# Generated by Django 6.0 on 2026-01-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('titulo_profissional', models.CharField(max_length=255)),
                ('bio_curta', models.TextField()),
                ('bio_longa', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('link_git', models.CharField()),
                ('link_linkedin', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao_curta', models.TextField()),
                ('descricao_detalhada', models.TextField()),
                ('thumb_projeto', models.ImageField(blank=True, null=True, upload_to='fotos/%d/%m/%Y/')),
                ('url_git', models.CharField()),
                ('tecnologias', models.CharField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('Avançado', 'Avançado')])),
                ('categoria', models.CharField(choices=[('linguagem', 'Linguagem'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('framework', 'Framework'), ('ferramenta', 'Ferramenta'), ('banco', 'Banco de Dados'), ('outros', 'Outros')])),
            ],
        ),
    ]
