# Generated by Django 6.0 on 2026-01-28 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0002_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='lido',
        ),
    ]
