# Generated by Django 6.0.5 on 2026-05-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_remove_contato_lido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link_git',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tecnologias',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='url_git',
            field=models.URLField(blank=True, null=True),
        ),
    ]
