# Generated by Django 6.0.5 on 2026-05-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0004_alter_profile_link_git_alter_profile_link_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
