# Generated by Django 6.0.5 on 2026-05-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0005_profile_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profissao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
