# Generated by Django 6.0.5 on 2026-05-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0006_profile_foco_profile_profissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stack_tecnologico',
            field=models.CharField(blank=True, help_text='Separe as tecnologias por vírgula. Ex: React, Django, Tailwind', max_length=255, null=True),
        ),
    ]
